name: ❓ Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context or information
      placeholder: Provide any relevant context...

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What have you already tried to solve this?
      placeholder: I've tried...

